### ISSUE TITLE
How to use the state switch card with multiple cards

### ISSUE THREAD

**Issue by mar005** [thomasloven/lovelace-state-switch#10]
In a very simple example I am trying to use the same home.yaml view to change the cards inside depending on the user and the browser used. I was using the custom header plugin to change the tabs but prefered to not create multiple yaml views and instead change the cards inside a view. Just noticed that the stateswitch card can't work on multiple card types inside. Not sure if this is an issue or it is as it was intended. My use case is what I explained above. There is another issue that someone opened about a user agent this would also be part of this as I notice a different device ID occurs on my Home Assistant iOS app depending on what wifi I am connected to as well.

`

`path: home
title: Home
icon: mdi:home-outline
cards:
- type: custom:state-switch
  entity: browser
  states:
    '9db2af23-ebf0b136':
    - type: entity-button
      entity: light.living_room
    - type: entity-button
      entity: light.bedroom
    '0d99987c-29470d4f':
      type: custom:button-card
      entity: light.bedroom
      name: Lamps
      icon: mdi:lamp
      show_state: true
      styles:
        card:
          - width: 100px
          - height: 100px
        grid:
          - grid-template-areas: '"i" "n" "s"'
          - grid-template-columns: 1fr
          - grid-template-rows: 1fr min-content min-content
        img_cell:
          - align-self: start
          - text-align: start
        name:
          - justify-self: start
          - padding-left: 10px
          - font-weight: bold
        state:
          - justify-self: start
          - padding-left: 10px
      state:
        - value: 'off'
          styles:
            card:
              - filter: opacity(50%)
            icon:
              - filter: grayscale(100%)
`

Not sure why my formatting is not working so apologies on the code. In general I have a simple setup with 2 lights in one state and the other with a custom button card for bedroom light for my mobile device.

**Comment by thomasloven** [comment]
Stacks
