### ISSUE TITLE
Different device ID depending on wifi network

### ISSUE THREAD

**Issue by mar005** [thomasloven/lovelace-state-switch#11]
I have noticed that the device ID will change depending on which wifi network I am in. Such as my work laptop browser will have a different device ID if I am at home vs at work. I will take some screenshots when I get home to show you what I am talking about.

**Comment by thomasloven** [comment]
It will change if you are using a different URL to access your instance, like https://myhome.duckdns.org vs http://hassio.local or http://192.158.0.5
