### ISSUE TITLE
Document card type

### ISSUE THREAD

**Issue by tjorim** [thomasloven/lovelace-state-switch#12]
Not sure if this card is of type js or module.

This isn't documented anywhere as stated [in another issue](https://github.com/thomasloven/lovelace-state-switch/issues/4):
> (I both tried "module" and "js", the documentation is not clear about this)

So what should it be? From a quick test it looks like both module and js work.

**Comment by caiosweet** [comment]
please you can correct the hacs installation path in the README.md
Thanks.

From
```
  - url: /local/state-switch.js
    type: module
```

to

```
  - url: /community_plugin/lovelace-state-switch/state-switch.js
    type: module
```

**Comment by thomasloven** [comment]
Fixed.

When in doubt, go with module. If that doesn't work, try js.
