### ISSUE TITLE
Transition not working in Safari and iOS app

### ISSUE THREAD

**Issue by vash3d** [thomasloven/lovelace-state-switch#17]
Are there some limitation with transition in safari and iOS app?
They are working nicely with chrome but in safari cards just change without the transition.

Edit: After restarting home assistant and clearing cache, they worked few times on Safari (not in the app) but then stopped again very soon.

**Comment by thomasloven** [comment]
Can't reproduce. Please try latest version.

**Comment by vash3d** [comment]
Ok I've started to setup Hassio from scratch (2 years old messy configuration) as soon as integrate the switch card I'll report back.

**Comment by vash3d** [comment]
Apologize for the very long delay. Working nicely now.
