### ISSUE TITLE
deviceID() is replaced with deviceID

### ISSUE THREAD

**Issue by zarya** [thomasloven/lovelace-state-switch#2]
https://github.com/thomasloven/lovelace-state-switch/blob/f06d3dba749e78ab312748a271e9deda0eeb3635/state-switch.js#L19

https://github.com/thomasloven/lovelace-state-switch/blob/f06d3dba749e78ab312748a271e9deda0eeb3635/state-switch.js#L41

see https://github.com/thomasloven/lovelace-card-tools/commit/8b9151f93b4d376a19b6786e0bd00421a87af5ff#diff-04c6e90faac2675aa89e2176d2eec7d8R84

**Comment by thomasloven** [comment]
Thank you. FIxed!
