### ISSUE TITLE
Custom element doesn't exist: state-switch

### ISSUE THREAD

**Issue by mvereecken** [thomasloven/lovelace-state-switch#4]
I tried to install the custom card, but it seems LL doesn't recognize it.
This is what I added in Lovelace:
```
- type: module
    url: /local/customcards/state-switch.js
```
(I both tried "module" and "js", the documentation is not clear about this)
The js-file was stored in www/customcards/state-switch.js
It's visible in the custom card list of the tracker-card, so it must be at least a little bit recognized :-).
Hass.io-version: 0.88.2
I also checked permissions; they are the same as the other custom cards.
Do you have any idea what can be wrong?

**Comment by mvereecken** [comment]
Also, I rebooted Home Assistant and my server a couple of times, just to make sure...

**Comment by mvereecken** [comment]
Also, I ruled out the fact that I use a subdirectory for the card, so it's now under www (root) /local/state-switch.js
The problem remains.

**Comment by mvereecken** [comment]
Some more info (Chrome debug)!
![image](https://user-images.githubusercontent.com/3824067/54197912-75f8da80-44c5-11e9-86d8-82fe78cf8fc9.png)
![image](https://user-images.githubusercontent.com/3824067/54197954-9163e580-44c5-11e9-8efb-78184d2394ea.png)

**Comment by thomasloven** [comment]
Do you have the latest version of card-tools?

**Comment by mvereecken** [comment]
Hi Thomas,

Yes I have:
![image](https://user-images.githubusercontent.com/3824067/54214628-dea47f00-44e6-11e9-8d8f-7d96c30c66cb.png)

**Comment by mvereecken** [comment]
Well... it turned out that, although the tracker shows the last version, it's not what was in the card-tools.js file! In the code it checks for 0.3 version, while in your latest source file it checks for 0.4. I don't know how this is possible, but anyway, it's not an error in your code. Thank you for making me think in the right direction :-). And keep up the good work, your tools are amazing!
