### ISSUE TITLE
Using significantly more column space (overlap) when used with history-graph card (affecting zoom factor on mobiles)

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-state-switch#52]
In addition to https://github.com/thomasloven/lovelace-state-switch/issues/41 the rare types of history-graph cards working with state-switch (the ones with a X and Y axis) result in the history cards using more space than allowed in their column.

I discovered this when using the mobile (smaller screen).

Without state-switch:
![grafik](https://user-images.githubusercontent.com/13799156/118379381-3a448880-b5da-11eb-8762-72ad864978dd.png)

With state-switch applied to history-graph card:
![grafik](https://user-images.githubusercontent.com/13799156/118379446-b6d76700-b5da-11eb-80fa-6364e8535c2f.png)

Please notice the automatically changed zoom factor. So the hole view is malformed on the mobile screen.

On a second view the zoom factor remains, but the graphes are cut (overlapping screen) instead.

state-switch really has some significant issues with history-graph card!

**Comment by mag1024** [comment]
@bcutter, do you have transitions enabled? If so, you might see if disabling them cures the problem.
I noticed similar behavior on the desktop, and in my case it was caused by the 'display: grid' that transitions insert.

**Comment by bcutter** [comment]
> 
> 
> @bcutter, do you have transitions enabled? If so, you might see if disabling them cures the problem.
> I noticed similar behavior on the desktop, and in my case it was caused by the 'display: grid' that transitions insert.

You´re right, this issue only appears when having a transition enabled.
BUT: As a workaround for history-graph cards showing up *at all*, it´s recommended to use transitions. See https://github.com/thomasloven/lovelace-state-switch/issues/41

So hard to decide... as described here https://github.com/thomasloven/lovelace-state-switch/issues/41#issuecomment-841715875 you can´t have em all, like "a history-graph of type 'laying bars' without any transition". Thomas needs to have a look into this as something´s just really mixed up here.

**Comment by bcutter** [comment]
In addition: the issue also exists for other cars types.

Here I have some mini graph cards in vertical stack cards as well as entities card, all put in state switch card which is in a vertical stack card.

![image](https://user-images.githubusercontent.com/13799156/139611315-ef0f14ac-618f-4550-aa3c-1669923e1b89.jpeg)

**Comment by thomasloven** [comment]
Please try release 1.9.3

**Comment by bcutter** [comment]
v1.9.3 rocks (so do you)! Fixed everything I mentioned earlier in this issue. Thank you.
