### ISSUE TITLE
Possible to add a delay between state changes

### ISSUE THREAD

**Issue by arboeh** [thomasloven/lovelace-state-switch#93]
Would be nice to have the posibility to add a delay between state changes. Sometimes its flipping too often. Im using it to change cards for "grid power import" and "grid power export". Sometimes the power is changing very often between grid-import and solar-export and thats why I asked for this enhancement.

**Comment by DEADSEC-SECURITY** [comment]
Have you tried `transition_time`
![Screenshot 2022-10-17 203256](https://user-images.githubusercontent.com/45077772/196266302-57391ee9-03c7-4a6c-9551-eaaa535c708d.png)

**Comment by arboeh** [comment]
Solved with a workaround by adding binary sensors with delay_on and delay_off.
